FROM php:8.2-apache
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    nano \
    libonig-dev \
    && docker-php-ext-install zip pdo pdo_mysql mbstring

RUN sed -i 's#DocumentRoot /var/www/html#DocumentRoot /var/www/html/public#g' \
    /etc/apache2/sites-available/000-default.conf \
    && a2enmod rewrite

RUN printf '<Directory /var/www/html/public>\n\
    AllowOverride All\n\
    Require all granted\n\
</Directory>\n' > /etc/apache2/conf-available/laravel.conf \
    && a2enconf laravel
    
COPY backend/ /var/www/html/
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN chown -R www-data:www-data /var/www/html

#RUN apt-get install composer
